title: My Website for me!
author: Dangerkin
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  
  Just going to add here! This is the tutorial website that I used to 
  learn how to use Github pages. I had to do this for a Comsci class.
  
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
